// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaIphone.Context;

#nullable disable

namespace TiendaIphone.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TiendaIphone.Models.Iphone", b =>
                {
                    b.Property<int>("IphoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IphoneID"), 1L, 1);

                    b.Property<int>("ColorIphone")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("EstadoIphone")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("TiendaID")
                        .HasColumnType("int");

                    b.HasKey("IphoneID");

                    b.HasIndex("TiendaID");

                    b.ToTable("Iphones", (string)null);
                });

            modelBuilder.Entity("TiendaIphone.Models.Tienda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NombreTienda")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tienda", (string)null);
                });

            modelBuilder.Entity("TiendaIphone.Models.Iphone", b =>
                {
                    b.HasOne("TiendaIphone.Models.Tienda", "Tienda")
                        .WithMany("ListadoIphone")
                        .HasForeignKey("TiendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("TiendaIphone.Models.Tienda", b =>
                {
                    b.Navigation("ListadoIphone");
                });
#pragma warning restore 612, 618
        }
    }
}
